name: 'Create Index from Collection'
description: 'Creates a pod index from a collection'

inputs:
  index_name_prefix:
    description: 'The prefix of the index name'
    required: false
    default: 'index-name'
  collection_name:
    description: 'The name of the collection to make the index from'
    required: true
  PINECONE_API_KEY:
    description: 'The Pinecone API key'
    required: true
  PINECONE_ENVIRONMENT:
    description: 'The environment of the collection'
    required: true
  dimension:
    description: 'The dimension of the index'
    required: false
    default: '3'
  metric:
    description: 'The metric of the index'
    required: false
    default: 'cosine'
  expected_vector_count:
    description: 'The expected number of vectors in the index'
    required: false

outputs:
  index_name:
    description: 'The name of the index, including randomized suffix'
    value: ${{ steps.create-index.outputs.index_name }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Setup Poetry
      uses: ./.github/actions/setup-poetry

    - name: Create index
      id: create-index
      shell: bash
      run: poetry run python3 scripts/3.x/create-pod-index-from-collection.py
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
        PINECONE_ENVIRONMENT: ${{ inputs.PINECONE_ENVIRONMENT }}
        INDEX_NAME_PREFIX: ${{ inputs.index_name_prefix }}
        COLLECTION_NAME: ${{ inputs.collection_name }}
        DIMENSION: ${{ inputs.dimension }}
        METRIC: ${{ inputs.metric }}
        EXPECTED_VECTOR_COUNT: ${{ inputs.expected_vector_count }}
        
