name: "Python Integration Tests (Control/Pod)"
'on':
  workflow_call:
    inputs:
      python-version:
        description: 'The version of python to install'
        required: false
        type: string
        default: '3.8'
      client-version:
        description: 'The version of the client to test with. Default is "dev" which runs tests with the head of main. But you can also specify published versions such as 3.0.2 to test with.'
        type: string
        default: dev
      environment:
        description: 'The environment where pod indexes will be created'
        required: false
        default: 'us-east1-gcp'
        type: string
      additional-headers-json:
        description: 'A json representation of additional headers you want passed with every request'
        required: false
        type: string
        # default: '{ "x-environment": "foo" }'
      dimension:
        description: 'The dimension of the index to create'
        required: false
        default: 1536
        type: number
      metric:
        description: 'The metric of the index to create'
        type: string
        required: false
        default: 'cosine'
      PINECONE_CONTROLLER_HOST:
        description: 'The control plane host. For staging, pass https://api-staging.pinecone.io'
        required: false
        default: 'https://api.pinecone.io'
        type: string
    secrets:
      PINECONE_API_KEY:
        required: true

jobs:
  python-control-pod:
    name: control plane
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Python ${{ inputs.python-version }}'
        uses: actions/setup-python@v4
        with:
          python-version: '${{ inputs.python-version }}'
      - name: Setup Poetry
        uses: ./.github/actions/setup-poetry
      - name: Install client
        if: ${{ inputs.client-version != 'dev' }}
        run: |
          rm -rf pinecone
          poetry add pinecone-client==${{ inputs.client-version }}
      - name: 'Run integration tests (REST, prod)'
        run: poetry run pytest tests/integration/control/pod -s -v
        env:
          PINECONE_CONTROLLER_HOST: ${{ inputs.PINECONE_CONTROLLER_HOST }}
          PINECONE_API_KEY: '${{ secrets.PINECONE_API_KEY }}'
          GITHUB_BUILD_NUMBER: '${{ github.run_number }}-p-${{ inputs.python-version}}'
          PINECONE_ENVIRONMENT: '${{ inputs.environment }}'
          ADDITIONAL_HEADERS_JSON: '${{ inputs.additional-headers-json}}'
          DIMENSION: ${{ inputs.dimension }}
          METRIC: ${{ inputs.metric }}