name: "Integration Tests (Data)"
'on':
  workflow_call: {}

jobs:
  data-plane-serverless:
    name: Data plane serverless integration tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        use_grpc: [true, false]
        metric: 
          - cosine
          # - euclidean
          # - dotproduct
        spec:
          - '{ "serverless": { "region": "us-west-2", "cloud": "aws" }}'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-data-plane
        with:
          use_grpc: '${{ matrix.use_grpc }}'
          metric: '${{ matrix.metric }}'
          spec: '${{ matrix.spec }}'
          PINECONE_API_KEY: '${{ secrets.PINECONE_API_KEY }}'
          freshness_timeout_seconds: 600

#   data-plane-pod:
#     name: Data plane pod integration tests
#     runs-on: ubuntu-latest
#     strategy:
#       max-parallel: 1
#       matrix:
#         use_grpc: [true, false]
#         metric: [cosine, dotproduct]
#         spec:
#           - '{ "pod": { "environment": "us-east1-gcp", "pod_type": "p1" }}'
#     steps:
#       - uses: actions/checkout@v4
#       - uses: ./.github/actions/test-data-plane
#         with:
#           use_grpc: '${{ matrix.use_grpc }}'
#           metric: '${{ matrix.metric }}'
#           spec: '${{ matrix.spec }}'
#           PINECONE_API_KEY: '${{ secrets.PINECONE_API_KEY }}'
